/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ymuh;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    public ArrayList<Integer> array  = new ArrayList<>(); 
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testNotEqualsArray(){
       
       
        ArrayList<Integer> array1 = new ArrayList<>(Arrays.asList(1,1,1)); 
        App.birikim(array, 2, 2, 2);
       
        assertNotEquals(array, array1);
    }
    @Test
    public void testNull(){
        
        
        assertNotNull(array);
    }

    @Test
    public void testNotNull(){
       
        App.birikim(array, 1, 1, 1);
        assertNotNull(array);
    }
}
